### ISSUE TITLE
CppLibs: 找不到指定的模块

### ISSUE THREAD

**Issue by Garbage123King** [yfismine/AlphaZero_Gomoku#2]
Traceback (most recent call last):
  File "D:\AlphaZeroGomoku-main\Scripts_function.py", line 11, in <module>
    from CppLibs import GomokuBoard, NeuralNet, MCTS
ImportError: DLL load failed while importing CppLibs: 找不到指定的模块。

我已经加了
import sys
sys.path.append(r"D:\AlphaZeroGomoku-main")
没用。

**Comment by yfismine** [comment]
路径没有指定对，可以看看CppLibs.pyd所在的位置
