### ISSUE TITLE
运行train.py时发生错误

### ISSUE THREAD

**Issue by Garbage123King** [yfismine/AlphaZero_Gomoku#3]
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from CppLibs import GomokuBoard, NeuralNet, MCTS
ImportError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

**Comment by yfismine** [comment]
路径问题，看一下能否找到CppLibs.pyd的位置，在pycharm里面设置一下根目录位置或者手动代码中添加改路径检索
